### PR TITLE
Update khan-exercises

### PR DESCRIPTION
**Pull request by mpolyak**
Issue: https://khanacademy.atlassian.net/browse/CP-3533

Test plan:
 - See https://github.com/Khan/khan-exercises/pull/161573

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@mpolyak with the caveat that I don't really know how to set this up locally and test it, the changes look reasonable to me.

If you'd like to to step through the test plan, I will need some additional documentation on getting this running I guess.

**Comment by danielhollas** [comment]
@matthewmorgan I am attaching my version of `app.py` where I commented out/deleted a bunch of stuff so that I don't have to connect to the S3 bucket where the actual graphies are stored (and I don't have the neccessary API key anyway). Running `python app.py` and opening port 5001 should hopefully work for you locally.

```python
#!/usr/bin/env python2
import hashlib
import json
import os
import re
import signal
import subprocess
import threading

import flask
from flask import request
import werkzeug.contrib.cache

import secrets

app = flask.Flask(__name__)
root = os.path.realpath(os.path.dirname(__file__))
cache = werkzeug.contrib.cache.SimpleCache()
cache.clear()


URL_REGEX = re.compile(
    r'https://([^/]+)/([a-f0-9]{40})\.svg')


class RenderTimeout(Exception):
    pass


@app.errorhandler(RenderTimeout)
def handle_timeout_error(error):
    return 'Rendering took too long, try again.', 500


@app.route('/', methods=['GET'])
def editor():
    return flask.render_template('editor.html')


@app.route('/svg', methods=['POST'])
def svg():
    """The external endpoint accessed to render a graphie

    Returns a web+graphie link as the response.
    """
    js = request.form['js']

    svg, other_data = _js_to_svg(js)

    hash = hashlib.sha1(js.encode('utf-8')).hexdigest()
    return 'FAKE_GRAPHIE'


@app.route('/svgize', methods=['POST'])
def svgize():
    """The rendering endpoint accessed by phantomjs"""
    js = request.form['js']
    return flask.render_template('plain_graph.html', js=js)
def run_with_timeout(command, timeout):
    """Run a command as a subprocess with a specified timeout in seconds

    If the subprocess successfully exits, this returns a string of output from
    the command. Otherwise, this returns `None`.
    """
    # An object of data that can be accessed inside the thread
    data = {}
    data['process'] = None
    data['stdout'] = None

    # The function to be run in a separate thread
    def thread_runner():
        data['process'] = subprocess.Popen(command, stdout=subprocess.PIPE,
                                           preexec_fn=os.setpgrp)
        data['stdout'] = data['process'].communicate()[0]

    thread = threading.Thread(target=thread_runner)
    thread.start()

    thread.join(timeout)
    if thread.is_alive():
        # If the thread is still running, kill it and ignore the output
        # os.killpg taken from http://stackoverflow.com/a/4791612/57318
        os.killpg(data['process'].pid, signal.SIGKILL)
        thread.join()
        return None
    else:
        return data['stdout']


def _js_to_svg(js):
    # subprocess.Popen() can't handle unicode, and phantomjs will produce
    # mangled results if we use js.encode('utf-8'). Note that JS allows
    # \u escapes in identifiers as well as in strings, so this approach
    # should work no matter where the non-ASCII characters are located.
    if isinstance(js, unicode):
        js = "".join([
            "\\u{0:04X}".format(ord(c)) if ord(c) > 127 else str(c)
            for c in js
        ])
    # Run phantomjs with a 55 second timeout. Gunicorn kills its child threads
    # after 60 seconds, so we need to kill the phantomjs thread before then.
    # TODO(csilvers): just use /usr/bin/timeout instead.
    json_data = run_with_timeout([
        os.path.join(root, 'node_modules', '.bin', 'phantomjs'),
        os.path.join(root, 'phantom_svg.js'),
        js
    ], 55)

    if json_data is None:
        raise RenderTimeout()

    data = json.loads(json_data)

    return data['svg'], data['other_data']

def _jsonp_wrap(data, func_name):
    return '%s(%s);' % (func_name, data)

if __name__ == "__main__":
    app.run(debug=True, port=5001, host='::')


```

**Comment by mpolyak** [comment]
@matthewmorgan if you clone this repo, then `git co update-khan-exercises` followed  by `python app.py` and open `localhost:5001`, follow test plan from https://github.com/Khan/khan-exercises/pull/161573

**Comment by matthewmorgan** [comment]
@danielhollas thanks I'll try that.

@mpolyak I did what you suggested, but `git co` wasn't recognized in that context, and I ended up need to install a number of dependencies manually.  I got the server running, but couldn't see any way to select the templates.  Maybe Daniel's server code will work...

**Comment by matthewmorgan** [comment]
I think it probably makes sense to just go ahead and merge this if Michael approves it.

**Comment by mpolyak** [comment]
Regular `git checkout` for the branch should work; you can apply khan-dot-files to the cloned repo by running `ka-clone --repair` in it.

**Comment by mpolyak** [comment]
> I think it probably makes sense to just go ahead and merge this if Michael approves it.

**Comment by mpolyak** [comment]
Err. I'm just going to merge it in.

**Comment by danielhollas** [comment]
@mpolyak awesome, thanks! LMK when it is deployed and I can test it out.

**Pull request merged**
